---

##dockerの有無チェック
- name: Check installed docker
  ansible.builtin.command:
    cmd: docker -v
  register: Check_docker
  ignore_errors: yes
  changed_when: false

##dockerインストール
- name: docker yum
  become: yes
  yum:
    name: docker
  when: Check_docker.failed
  changed_when: false

##docker起動
- name: start docker
  ansible.builtin.systemd:
    name: docker
    state: start
  become: yes
  ignore_errors: yes

##docker自動起動設定
- name: enabled docker
  ansible.builtin.systemd:
    name: docker
    state: enabled
  become: yes
  ignore_errors: yes

