---
- name: Check installed session-manager-plugin
  ansible.builtin.command:
    cmd: session-manager-plugin
  register: Check_plugin
  ignore_errors: yes
  changed_when: false

- name: Download session-manager-plugin
  ansible.builtin.shell:
    cmd: curl -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
  when: "'The Session Manager plugin was installed successfully' not in Check_plugin"
  changed_when: false

- name: Install session-manager-plugin
  become: yes
  ansible.builtin.shell:
    cmd: yum install -y ./SessionManagerPluginSetup.exe
lugin.rpm
  when: "'The Session Manager plugin was installed successfully' not in Check_plugin"
  changed_when: false
